
import { ElementData } from './types';

export const ELEMENTS: ElementData[] = [
  { z: 1, symbol: "H", name: "Hydrogen", mass: 1.008, neutrons: 0, state: "Khí", category: "Phi kim", physical: "Khí không màu, không mùi, nhẹ nhất trong các chất khí.", natural: "Nguyên tố phổ biến nhất trong vũ trụ.", applications: "Nhiên liệu tên lửa, sản xuất phân bón (ammonia)." },
  { z: 2, symbol: "He", name: "Helium", mass: 4.003, neutrons: 2, state: "Khí", category: "Khí hiếm", physical: "Khí trơ, không màu, không mùi, độ dẫn nhiệt cao.", natural: "Phổ biến thứ hai trong vũ trụ, tìm thấy trong các mỏ khí tự nhiên.", applications: "Bơm bóng bay, làm mát máy quét MRI." },
  { z: 3, symbol: "Li", name: "Lithium", mass: 6.94, neutrons: 4, state: "Rắn", category: "Kim loại kiềm", physical: "Kim loại mềm, màu bạc, nhẹ nhất.", natural: "Tìm thấy trong các khoáng vật như spodumene.", applications: "Sản xuất pin sạc cho điện thoại, laptop, xe điện." },
  { z: 4, symbol: "Be", name: "Beryllium", mass: 9.012, neutrons: 5, state: "Rắn", category: "Kim loại kiềm thổ", physical: "Cứng, giòn, màu xám thép.", natural: "Tìm thấy chủ yếu trong khoáng vật beryl (ngọc lục bảo).", applications: "Linh kiện máy bay, vệ tinh, cửa sổ máy X-quang." },
  { z: 5, symbol: "B", name: "Boron", mass: 10.81, neutrons: 6, state: "Rắn", category: "Á kim", physical: "Chất rắn màu đen, rất cứng.", natural: "Tìm thấy trong các mỏ borax.", applications: "Sản xuất thủy tinh chịu nhiệt, chất tẩy rửa." },
  { z: 6, symbol: "C", name: "Carbon", mass: 12.011, neutrons: 6, state: "Rắn", category: "Phi kim", physical: "Tồn tại dưới dạng kim cương hoặc than chì.", natural: "Cơ sở của mọi sự sống hữu cơ.", applications: "Làm trang sức, nhiên liệu, vật liệu composite." },
  { z: 7, symbol: "N", name: "Nitrogen", mass: 14.007, neutrons: 7, state: "Khí", category: "Phi kim", physical: "Khí không màu, không mùi, chiếm 78% không khí.", natural: "Thành phần quan trọng trong protein và DNA.", applications: "Làm lạnh thực phẩm, sản xuất phân đạm." },
  { z: 8, symbol: "O", name: "Oxygen", mass: 15.999, neutrons: 8, state: "Khí", category: "Phi kim", physical: "Hỗ trợ sự cháy và hô hấp của sinh vật.", natural: "Chiếm khoảng 21% thể tích khí quyển.", applications: "Dùng trong y tế, cắt gọt kim loại, thám hiểm không gian." },
  { z: 9, symbol: "F", name: "Fluorine", mass: 18.998, neutrons: 10, state: "Khí", category: "Halogen", physical: "Khí màu vàng nhạt, cực kỳ phản ứng.", natural: "Tìm thấy trong khoáng vật fluorite.", applications: "Chống sâu răng (trong kem đánh răng), sản xuất Teflon." },
  { z: 10, symbol: "Ne", name: "Neon", mass: 20.180, neutrons: 10, state: "Khí", category: "Khí hiếm", physical: "Phát sáng màu đỏ cam rực rỡ khi có dòng điện đi qua.", natural: "Chiết xuất từ việc chưng cất phân đoạn không khí lỏng.", applications: "Biển quảng cáo, đèn chỉ thị." },
  { z: 11, symbol: "Na", name: "Sodium", mass: 22.990, neutrons: 12, state: "Rắn", category: "Kim loại kiềm", physical: "Rất mềm, màu trắng bạc, phản ứng mãnh liệt với nước.", natural: "Thành phần chính trong muối ăn (NaCl).", applications: "Chất trao đổi nhiệt, sản xuất xà phòng." },
  { z: 12, symbol: "Mg", name: "Magnesium", mass: 24.305, neutrons: 12, state: "Rắn", category: "Kim loại kiềm thổ", physical: "Kim loại nhẹ, cháy với ánh sáng trắng chói.", natural: "Phổ biến trong nước biển và vỏ Trái Đất.", applications: "Hợp kim hàng không, pháo hoa." },
  { z: 13, symbol: "Al", name: "Aluminum", mass: 26.982, neutrons: 14, state: "Rắn", category: "Kim loại", physical: "Dẫn điện, dẫn nhiệt tốt, chống ăn mòn.", natural: "Nằm trong quặng bauxite.", applications: "Vỏ máy bay, lon nước giải khát, dây điện." },
  { z: 14, symbol: "Si", name: "Silicon", mass: 28.086, neutrons: 14, state: "Rắn", category: "Á kim", physical: "Màu xám tối, ánh kim, có tính bán dẫn.", natural: "Chiếm phần lớn khối lượng cát (SiO2).", applications: "Linh kiện điện tử, chip máy tính, pin mặt trời." },
  { z: 15, symbol: "P", name: "Phosphorus", mass: 30.974, neutrons: 16, state: "Rắn", category: "Phi kim", physical: "Tồn tại ở dạng phốt pho trắng hoặc đỏ.", natural: "Cần thiết cho xương, răng và ATP trong cơ thể.", applications: "Sản xuất diêm, phân bón, thuốc trừ sâu." },
  { z: 16, symbol: "S", name: "Sulfur", mass: 32.06, neutrons: 16, state: "Rắn", category: "Phi kim", physical: "Chất rắn màu vàng, giòn.", natural: "Tìm thấy ở trạng thái tự do gần núi lửa.", applications: "Sản xuất axit sulfuric, lưu hóa cao su." },
  { z: 17, symbol: "Cl", name: "Chlorine", mass: 35.45, neutrons: 18, state: "Khí", category: "Halogen", physical: "Khí màu vàng lục, mùi hắc, độc.", natural: "Sản xuất từ điện phân nước muối.", applications: "Khử trùng nước sinh hoạt, chất tẩy trắng." },
  { z: 18, symbol: "Ar", name: "Argon", mass: 39.948, neutrons: 22, state: "Khí", category: "Khí hiếm", physical: "Khí trơ tuyệt đối, không màu.", natural: "Khí hiếm phổ biến nhất trong không khí.", applications: "Môi trường bảo vệ trong hàn kim loại, bóng đèn dây tóc." },
  { z: 19, symbol: "K", name: "Potassium", mass: 39.098, neutrons: 20, state: "Rắn", category: "Kim loại kiềm", physical: "Kim loại cực mềm, màu bạc, có thể cắt bằng dao.", natural: "Rất quan trọng cho sự phát triển của thực vật.", applications: "Sản xuất phân bón kali, thuốc nổ." },
  { z: 20, symbol: "Ca", name: "Calcium", mass: 40.078, neutrons: 20, state: "Rắn", category: "Kim loại kiềm thổ", physical: "Màu xám bạc, cứng hơn chì.", natural: "Thành phần chính của xương, răng và vỏ sò.", applications: "Vật liệu xây dựng (xi măng), thực phẩm bổ sung." },
  { z: 21, symbol: "Sc", name: "Scandium", mass: 44.956, neutrons: 24, state: "Rắn", category: "Kim loại chuyển tiếp", physical: "Nhẹ, màu trắng bạc, điểm nóng chảy cao.", natural: "Hiếm khi tìm thấy ở dạng tập trung.", applications: "Hợp kim nhôm-scandium cho gậy bóng chày và xe đạp." },
  { z: 22, symbol: "Ti", name: "Titanium", mass: 47.867, neutrons: 26, state: "Rắn", category: "Kim loại chuyển tiếp", physical: "Cực kỳ bền, nhẹ và chống ăn mòn rất tốt.", natural: "Tìm thấy trong hầu hết các loại đá phun trào.", applications: "Bộ phận máy bay phản lực, cấy ghép y khoa, vỏ tàu thủy." },
  { z: 23, symbol: "V", name: "Vanadium", mass: 50.942, neutrons: 28, state: "Rắn", category: "Kim loại chuyển tiếp", physical: "Cứng, màu xám trắng, dẻo.", natural: "Tìm thấy trong nhiều loại khoáng vật và dầu mỏ.", applications: "Sản xuất thép siêu bền cho dụng cụ cầm tay và động cơ." },
  { z: 24, symbol: "Cr", name: "Chromium", mass: 51.996, neutrons: 28, state: "Rắn", category: "Kim loại chuyển tiếp", physical: "Cực kỳ cứng, có khả năng đánh bóng rất cao.", natural: "Tên gọi bắt nguồn từ tiếng Hy Lạp 'chroma' nghĩa là màu sắc.", applications: "Mạ crôm cho xe hơi, sản xuất thép không gỉ (inox)." },
  { z: 25, symbol: "Mn", name: "Manganese", mass: 54.938, neutrons: 30, state: "Rắn", category: "Kim loại chuyển tiếp", physical: "Màu xám hồng, rất giòn và cứng.", natural: "Phổ biến trong vỏ Trái Đất, thường ở dạng quặng dioxide.", applications: "Sản xuất thép, làm pin khô, sản xuất đồ gốm." },
  { z: 26, symbol: "Fe", name: "Iron", mass: 55.845, neutrons: 30, state: "Rắn", category: "Kim loại chuyển tiếp", physical: "Màu xám sáng, có tính từ tính mạnh.", natural: "Thành phần chính của lõi Trái Đất và hemoglobin trong máu.", applications: "Vật liệu xây dựng, sản xuất thép, máy móc." },
  { z: 27, symbol: "Co", name: "Cobalt", mass: 58.933, neutrons: 32, state: "Rắn", category: "Kim loại chuyển tiếp", physical: "Màu xanh bạc, có tính từ tính.", natural: "Thường tìm thấy cùng với đồng và niken.", applications: "Nam châm vĩnh cửu, hợp kim chịu nhiệt, pin lithium-ion." },
  { z: 28, symbol: "Ni", name: "Nickel", mass: 58.693, neutrons: 31, state: "Rắn", category: "Kim loại chuyển tiếp", physical: "Màu trắng bạc, cứng, dẻo và dễ rèn.", natural: "Tìm thấy nhiều trong các thiên thạch sắt.", applications: "Tiền xu, thép không gỉ, mạ điện bảo vệ kim loại." },
  { z: 29, symbol: "Cu", name: "Copper", mass: 63.546, neutrons: 35, state: "Rắn", category: "Kim loại chuyển tiếp", physical: "Màu đỏ đặc trưng, dẫn điện và dẫn nhiệt cực tốt.", natural: "Một trong số ít kim loại tồn tại ở dạng nguyên chất.", applications: "Dây dẫn điện, ống nước, đúc tượng." },
  { z: 30, symbol: "Zn", name: "Zinc", mass: 65.38, neutrons: 35, state: "Rắn", category: "Kim loại chuyển tiếp", physical: "Màu xám xanh, giòn ở nhiệt độ thường.", natural: "Tìm thấy trong quặng sphalerite.", applications: "Mạ kẽm chống rỉ, hợp kim đồng thau, pin." },
  { z: 31, symbol: "Ga", name: "Gallium", mass: 69.723, neutrons: 39, state: "Rắn", category: "Kim loại", physical: "Có thể tan chảy ngay trong lòng bàn tay (nóng chảy ở 29.7°C).", natural: "Không tồn tại ở dạng tự do.", applications: "Chất bán dẫn, đèn LED, nhiệt kế nhiệt độ cao." },
  { z: 32, symbol: "Ge", name: "Germanium", mass: 72.630, neutrons: 41, state: "Rắn", category: "Á kim", physical: "Màu trắng xám, bóng, có cấu trúc tinh thể giống kim cương.", natural: "Tìm thấy trong quặng kẽm và một số loại than đá.", applications: "Ống kính hồng ngoại, sợi quang học, pin mặt trời." },
  { z: 33, symbol: "As", name: "Arsenic", mass: 74.922, neutrons: 42, state: "Rắn", category: "Á kim", physical: "Tồn tại dưới nhiều dạng (đen, xám, vàng), rất độc.", natural: "Tìm thấy trong khoáng vật arsenopyrite.", applications: "Chất bán dẫn, bảo quản gỗ (hạn chế dần)." },
  { z: 34, symbol: "Se", name: "Selenium", mass: 78.971, neutrons: 45, state: "Rắn", category: "Phi kim", physical: "Độ dẫn điện thay đổi theo cường độ ánh sáng.", natural: "Tìm thấy trong quặng sulfide.", applications: "Máy photocopy, tế bào quang điện, bổ sung dinh dưỡng." },
  { z: 35, symbol: "Br", name: "Bromine", mass: 79.904, neutrons: 45, state: "Lỏng", category: "Halogen", physical: "Chất lỏng màu đỏ nâu, bốc khói hắc, rất độc.", natural: "Tìm thấy chủ yếu trong nước biển dưới dạng muối.", applications: "Chất chống cháy, thuốc nhuộm, nhiếp ảnh phim." },
  { z: 36, symbol: "Kr", name: "Krypton", mass: 83.798, neutrons: 48, state: "Khí", category: "Khí hiếm", physical: "Khí trơ, phát sáng trắng xanh khi có điện chạy qua.", natural: "Tồn tại với lượng rất nhỏ trong khí quyển.", applications: "Đèn flash chụp ảnh tốc độ cao, cửa sổ cách nhiệt cao cấp." },
];

export const GROUPS = [
  { id: 'Helium', name: 'Đứa Con Của Mặt Trời', icon: '☀️', color: 'from-orange-400 to-red-500' },
  { id: 'Neon', name: 'Ánh Sáng Thành Thị', icon: '🌃', color: 'from-purple-400 to-pink-500' },
  { id: 'Argon', name: 'Gã Khổng Lồ Lười Biếng', icon: '😴', color: 'from-blue-400 to-indigo-500' },
  { id: 'Krypton', name: 'Kẻ Ẩn Mình', icon: '🕵️', color: 'from-green-400 to-teal-500' }
];

export const SHELL_CAPACITIES = [2, 8, 18, 32];
